version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/build

  nginx:
    build: ./nginx/
    volumes:
      - static:/usr/share/nginx/html/
      - media:/media/
    ports:
      - "80:80"